apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "springapp.fullname" . }}
  labels:
    {{- include "springapp.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "springapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "springapp.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
      - name: configmap
        configMap:
          name: common-configmap
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["java"]
          args: ["-jar", "SimpleSpringBootApp.jar"]
          volumeMounts:
          - name: configmap
            mountPath: "/var/lib"
            readOnly: true
          ports:
            - name: springapp-port
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /hello
              port: springapp-port
          readinessProbe:
            httpGet:
              path: /hello
              port: springapp-port
      imagePullSecrets:
        - name: regsecret
